In [0]:
/import numpy as np

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing
import numpy as np
arr1=np.arange(20).reshape(4,5)
k=arr1[:,[0]]
arr1[:,[0]]=arr1[:,[3]]
arr1[:,[3]]=k
print(arr1)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 3  1  2  0  4]
 [ 8  6  7  5  9]
 [13 11 12 10 14]
 [18 16 17 15 19]]


In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row
arr1=arr1=np.arange(20).reshape(4,5)
for i in range(2):
 m=arr1[[i]]
 arr1[[i]]=arr1[[3-i]]
 arr1[[3-i]]=m
print(arr1)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
print(arr2)
k=np.mean(arr2[np.isnan(arr2)!=True])
arr2[np.isnan(arr2)]=k
print(arr2)



[[ 1.  2. nan]
 [ 4.  5.  6.]
 [nan nan  9.]]
[[1.  2.  4.5]
 [4.  5.  6. ]
 [4.5 4.5 9. ]]


In [0]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3
import numpy as np
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
print(arr3)
print(arr3[(arr3>25) | (arr3%3==0)])


[[58 14 63 64]
 [ 8 52  8 78]
 [19 63 31 23]
 [76 28 69 16]
 [19 29 76 91]]
[58 63 64 52 78 63 31 76 28 69 29 76 91]


In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
print("the 10th percentlie",np.percentile(arr3,10))
print("the 25th percentile",np.percentile(arr3,25))
print("the 50th percentile",np.percentile(arr3,50))

   


# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
#   
# Hint: to solve this function google np.percentile()

the 10th percentlie 14.900000000000002
the 25th percentile 35.75
the 50th percentile 49.0
