In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1
import numpy as np
arr1=np.arange(40).reshape(8,5)
arr1[:,::2]


array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 
import numpy as np
arr1=np.arange(40).reshape(8,5)
arr1[::3,::2]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100
# Q3. Write a code to normalize arr2.
import numpy as np
arr2=np.random.randint(low=1, high=100, size=10).reshape(2,5)
print(arr2)
k=np.amax(arr2)
y=np.amin(arr2)
for i in range(2) :
 for j in range(5):
   arr2[i][j]=(arr2[i][j]-y)/(k-y)
print(arr2)



[[ 3 66 54 91 76]
 [ 7 36 44 77 30]]
[[0 0 0 1 0]
 [0 0 0 0 0]]


 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.
d={}
for i in

In [0]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai

In [35]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
import numpy as np
def maximum(k,b):
 arr1=np.array(k)
 l2=arr1.tolist()
 
 if b<=len(l2):
  for i in range (b):
    k=max(l2)
    l2.remove(k)
  print(k)  
 else:
   print("Limit exceeded") 
maximum((12,34,40,7,1,0),3)


 
  
 


12


In [0]:
import numpy as np
arr1=np.arange(40).reshape(8,5)
arr1[:,::2]



array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])